// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: app_branding.sql

package database

import (
	"context"
	"database/sql"
)

const getAppBranding = `-- name: GetAppBranding :one
SELECT id, app_name, primary_color, accent_color, app_logo, app_logo_on_dark, client_name, client_logo, created_at, updated_at FROM app_branding
WHERE id = 1
`

func (q *Queries) GetAppBranding(ctx context.Context) (AppBranding, error) {
	row := q.db.QueryRowContext(ctx, getAppBranding)
	var i AppBranding
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.AppLogo,
		&i.AppLogoOnDark,
		&i.ClientName,
		&i.ClientLogo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAppBranding = `-- name: UpsertAppBranding :one
INSERT INTO app_branding (
  id,
  app_name,
  primary_color,
  accent_color,
  app_logo,
  app_logo_on_dark,
  client_name,
  client_logo
) VALUES (
  1,
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
ON CONFLICT (id) DO UPDATE
SET app_name         = EXCLUDED.app_name,
    primary_color    = EXCLUDED.primary_color,
    accent_color     = EXCLUDED.accent_color,
    app_logo         = EXCLUDED.app_logo,
    app_logo_on_dark = EXCLUDED.app_logo_on_dark,
    client_name      = EXCLUDED.client_name,
    client_logo      = EXCLUDED.client_logo
RETURNING id, app_name, primary_color, accent_color, app_logo, app_logo_on_dark, client_name, client_logo, created_at, updated_at
`

type UpsertAppBrandingParams struct {
	AppName       string         `json:"app_name"`
	PrimaryColor  string         `json:"primary_color"`
	AccentColor   string         `json:"accent_color"`
	AppLogo       sql.NullString `json:"app_logo"`
	AppLogoOnDark sql.NullString `json:"app_logo_on_dark"`
	ClientName    sql.NullString `json:"client_name"`
	ClientLogo    sql.NullString `json:"client_logo"`
}

func (q *Queries) UpsertAppBranding(ctx context.Context, arg UpsertAppBrandingParams) (AppBranding, error) {
	row := q.db.QueryRowContext(ctx, upsertAppBranding,
		arg.AppName,
		arg.PrimaryColor,
		arg.AccentColor,
		arg.AppLogo,
		arg.AppLogoOnDark,
		arg.ClientName,
		arg.ClientLogo,
	)
	var i AppBranding
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.AppLogo,
		&i.AppLogoOnDark,
		&i.ClientName,
		&i.ClientLogo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
