// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: findings.sql
//
// NOTE: sqlc cannot run on the maintainers' macOS toolchain (pg_query_go cgo
// `strchrnul` redeclaration vs the macOS SDK), so this file is hand-authored to
// mirror sqlc's output exactly. Keep it in sync with sqlc/models/findings.sql.

package database

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createFinding = `-- name: CreateFinding :one
INSERT INTO findings (
  flow_id, derive_run_id, title, severity, cvss_score, cvss_vector, cwe, category,
  affected, description, business_impact, likelihood, impact, remediation,
  "references", attack_path, repro_steps, evidence, source_task_ids, evidence_refs, provenance
) VALUES (
  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21
) RETURNING id, flow_id, derive_run_id, title, severity, cvss_score, cvss_vector, cwe, category, affected, description, business_impact, likelihood, impact, remediation, "references", attack_path, repro_steps, evidence, source_task_ids, evidence_refs, provenance, created_at, updated_at, retest_status
`

type CreateFindingParams struct {
	FlowID         int64           `json:"flow_id"`
	DeriveRunID    sql.NullInt64   `json:"derive_run_id"`
	Title          string          `json:"title"`
	Severity       string          `json:"severity"`
	CvssScore      sql.NullFloat64 `json:"cvss_score"`
	CvssVector     sql.NullString  `json:"cvss_vector"`
	Cwe            sql.NullString  `json:"cwe"`
	Category       sql.NullString  `json:"category"`
	Affected       json.RawMessage `json:"affected"`
	Description    string          `json:"description"`
	BusinessImpact sql.NullString  `json:"business_impact"`
	Likelihood     sql.NullInt16   `json:"likelihood"`
	Impact         sql.NullInt16   `json:"impact"`
	Remediation    sql.NullString  `json:"remediation"`
	References     json.RawMessage `json:"references"`
	AttackPath     json.RawMessage `json:"attack_path"`
	ReproSteps     json.RawMessage `json:"repro_steps"`
	Evidence       sql.NullString  `json:"evidence"`
	SourceTaskIds  json.RawMessage `json:"source_task_ids"`
	EvidenceRefs   json.RawMessage `json:"evidence_refs"`
	Provenance     json.RawMessage `json:"provenance"`
}

func (q *Queries) CreateFinding(ctx context.Context, arg CreateFindingParams) (Finding, error) {
	row := q.db.QueryRowContext(ctx, createFinding,
		arg.FlowID,
		arg.DeriveRunID,
		arg.Title,
		arg.Severity,
		arg.CvssScore,
		arg.CvssVector,
		arg.Cwe,
		arg.Category,
		arg.Affected,
		arg.Description,
		arg.BusinessImpact,
		arg.Likelihood,
		arg.Impact,
		arg.Remediation,
		arg.References,
		arg.AttackPath,
		arg.ReproSteps,
		arg.Evidence,
		arg.SourceTaskIds,
		arg.EvidenceRefs,
		arg.Provenance,
	)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.DeriveRunID,
		&i.Title,
		&i.Severity,
		&i.CvssScore,
		&i.CvssVector,
		&i.Cwe,
		&i.Category,
		&i.Affected,
		&i.Description,
		&i.BusinessImpact,
		&i.Likelihood,
		&i.Impact,
		&i.Remediation,
		&i.References,
		&i.AttackPath,
		&i.ReproSteps,
		&i.Evidence,
		&i.SourceTaskIds,
		&i.EvidenceRefs,
		&i.Provenance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetestStatus,
	)
	return i, err
}

const createFindingDerivation = `-- name: CreateFindingDerivation :one
INSERT INTO finding_derivations (flow_id, status, model, provider)
VALUES ($1, $2, $3, $4) RETURNING id, flow_id, status, model, provider, summary, error, created_at, updated_at
`

type CreateFindingDerivationParams struct {
	FlowID   int64          `json:"flow_id"`
	Status   string         `json:"status"`
	Model    sql.NullString `json:"model"`
	Provider sql.NullString `json:"provider"`
}

func (q *Queries) CreateFindingDerivation(ctx context.Context, arg CreateFindingDerivationParams) (FindingDerivation, error) {
	row := q.db.QueryRowContext(ctx, createFindingDerivation,
		arg.FlowID,
		arg.Status,
		arg.Model,
		arg.Provider,
	)
	var i FindingDerivation
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Status,
		&i.Model,
		&i.Provider,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFlowFindings = `-- name: DeleteFlowFindings :exec
DELETE FROM findings WHERE flow_id = $1
`

func (q *Queries) DeleteFlowFindings(ctx context.Context, flowID int64) error {
	_, err := q.db.ExecContext(ctx, deleteFlowFindings, flowID)
	return err
}

const getFinding = `-- name: GetFinding :one
SELECT id, flow_id, derive_run_id, title, severity, cvss_score, cvss_vector, cwe, category, affected, description, business_impact, likelihood, impact, remediation, "references", attack_path, repro_steps, evidence, source_task_ids, evidence_refs, provenance, created_at, updated_at, retest_status FROM findings WHERE id = $1
`

func (q *Queries) GetFinding(ctx context.Context, id int64) (Finding, error) {
	row := q.db.QueryRowContext(ctx, getFinding, id)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.DeriveRunID,
		&i.Title,
		&i.Severity,
		&i.CvssScore,
		&i.CvssVector,
		&i.Cwe,
		&i.Category,
		&i.Affected,
		&i.Description,
		&i.BusinessImpact,
		&i.Likelihood,
		&i.Impact,
		&i.Remediation,
		&i.References,
		&i.AttackPath,
		&i.ReproSteps,
		&i.Evidence,
		&i.SourceTaskIds,
		&i.EvidenceRefs,
		&i.Provenance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetestStatus,
	)
	return i, err
}

const getFlowFindings = `-- name: GetFlowFindings :many
SELECT id, flow_id, derive_run_id, title, severity, cvss_score, cvss_vector, cwe, category, affected, description, business_impact, likelihood, impact, remediation, "references", attack_path, repro_steps, evidence, source_task_ids, evidence_refs, provenance, created_at, updated_at, retest_status FROM findings WHERE flow_id = $1
ORDER BY (CASE severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1
  WHEN 'medium' THEN 2 WHEN 'low' THEN 3 ELSE 4 END), created_at DESC
`

func (q *Queries) GetFlowFindings(ctx context.Context, flowID int64) ([]Finding, error) {
	rows, err := q.db.QueryContext(ctx, getFlowFindings, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.DeriveRunID,
			&i.Title,
			&i.Severity,
			&i.CvssScore,
			&i.CvssVector,
			&i.Cwe,
			&i.Category,
			&i.Affected,
			&i.Description,
			&i.BusinessImpact,
			&i.Likelihood,
			&i.Impact,
			&i.Remediation,
			&i.References,
			&i.AttackPath,
			&i.ReproSteps,
			&i.Evidence,
			&i.SourceTaskIds,
			&i.EvidenceRefs,
			&i.Provenance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetestStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestFlowDerivation = `-- name: GetLatestFlowDerivation :one
SELECT id, flow_id, status, model, provider, summary, error, created_at, updated_at FROM finding_derivations WHERE flow_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestFlowDerivation(ctx context.Context, flowID int64) (FindingDerivation, error) {
	row := q.db.QueryRowContext(ctx, getLatestFlowDerivation, flowID)
	var i FindingDerivation
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Status,
		&i.Model,
		&i.Provider,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setFindingRetestStatus = `-- name: SetFindingRetestStatus :one
UPDATE findings SET retest_status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND flow_id = $3
RETURNING id, flow_id, derive_run_id, title, severity, cvss_score, cvss_vector, cwe, category, affected, description, business_impact, likelihood, impact, remediation, "references", attack_path, repro_steps, evidence, source_task_ids, evidence_refs, provenance, created_at, updated_at, retest_status
`

type SetFindingRetestStatusParams struct {
	ID           int64  `json:"id"`
	RetestStatus string `json:"retest_status"`
	FlowID       int64  `json:"flow_id"`
}

func (q *Queries) SetFindingRetestStatus(ctx context.Context, arg SetFindingRetestStatusParams) (Finding, error) {
	row := q.db.QueryRowContext(ctx, setFindingRetestStatus, arg.ID, arg.RetestStatus, arg.FlowID)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.DeriveRunID,
		&i.Title,
		&i.Severity,
		&i.CvssScore,
		&i.CvssVector,
		&i.Cwe,
		&i.Category,
		&i.Affected,
		&i.Description,
		&i.BusinessImpact,
		&i.Likelihood,
		&i.Impact,
		&i.Remediation,
		&i.References,
		&i.AttackPath,
		&i.ReproSteps,
		&i.Evidence,
		&i.SourceTaskIds,
		&i.EvidenceRefs,
		&i.Provenance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetestStatus,
	)
	return i, err
}

const updateFindingDerivationStatus = `-- name: UpdateFindingDerivationStatus :one
UPDATE finding_derivations SET status = $1, summary = $2, error = $3 WHERE id = $4 RETURNING id, flow_id, status, model, provider, summary, error, created_at, updated_at
`

type UpdateFindingDerivationStatusParams struct {
	Status  string         `json:"status"`
	Summary sql.NullString `json:"summary"`
	Error   sql.NullString `json:"error"`
	ID      int64          `json:"id"`
}

func (q *Queries) UpdateFindingDerivationStatus(ctx context.Context, arg UpdateFindingDerivationStatusParams) (FindingDerivation, error) {
	row := q.db.QueryRowContext(ctx, updateFindingDerivationStatus,
		arg.Status,
		arg.Summary,
		arg.Error,
		arg.ID,
	)
	var i FindingDerivation
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Status,
		&i.Model,
		&i.Provider,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
